name: Just Linter

on:
  push:
    branches: [ materialize ]

jobs:

  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@v1.0.1
      with:
        # Required:
        url: 'https://...'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: 'github,google'
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"